### PR TITLE
Fix navigation for touchscreen devices

### LINKED ISSUE #992: Menu Links Don't Work on Touchscreens
#### Issue Summary

Top level menu links don't work on touch screens.
When you press them, nothing happens.

image

### PR DESCRIPTION
**Pull request by NetOperatorWibby**
### Description

What it says on the tin.

Also updates the `dev.sh` script to allow for running this repo on one's computer and accessing it over a local network for testing on different devices (like, a tablet).

### Fixes
Closes #992

### CODE REVIEW

File: dev.sh [hunk 1]
```diff
@@ -19,4 +19,4 @@ $DIR/hooks/install.sh
 
 $PHPBIN composer.phar install
 git submodule update --init
-$PHPBIN --server localhost:8000 --docroot "$DIR/web" "$DIR/web/index.php"
```
Comment (kauffj) [inline dev.sh]: Is this change correct?
